----------------------------------------               
----------------------------------------               
2022-04-01 14:39:45.2046 ERROR Message: ServicioFacturaVenta >> RegistroDeCobro                
	ErrorTitle: ServicioFacturaVenta >> RegistroDeCobro               
	ErrorSummary: No pudo ejecutar ActualizarPresupuestoCliente - System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Instrucción UPDATE en conflicto con la restricción FOREIGN KEY "FK_Cliente_GrupoPresupuesto". El conflicto ha aparecido en la base de datos "ecommerce", tabla "dbo.GrupoPresupuesto", column 'Id'.
Se terminó la instrucción.
   en System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   en System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   en System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   en System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   en System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   en System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   en System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   en System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   en System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   en System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<NonQuery>b__0(DbCommand t, DbCommandInterceptionContext`1 c)
   en System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   en System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   en System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   en System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   en System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   en System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   en System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   en System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   en System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
   en System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   en System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   en System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
   en System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   en System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   en System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   en System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Data.Entity.Internal.InternalContext.SaveChanges()
   en System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   en System.Data.Entity.DbContext.SaveChanges()
   en Datos.Repositorios.ClienteRepositorio.ActualizarPresupuesto(Cliente model) en D:\sac\sac\SAC\Datos\Repositorios\ClienteRepositorio.cs:línea 241
   en Negocio.Servicios.ServicioCliente.ActualizarPresupuestoCliente(ClienteModel model) en D:\sac\sac\SAC\Negocio\Servicios\ServicioCliente.cs:línea 255               
	ErrorDetails:    en Negocio.Servicios.ServicioCliente.ActualizarPresupuestoCliente(ClienteModel model) en D:\sac\sac\SAC\Negocio\Servicios\ServicioCliente.cs:línea 260
   en Negocio.Servicios.ServicioFacturaVenta.RegistroDeCobro(List`1 cobroFacturaModel, CobroFacturaModoModel medioCobro, Int32 IdTipoComprobanteVenta) en D:\sac\sac\SAC\Negocio\Servicios\ServicioFacturaVenta.cs:línea 616
